### Local OK
GET http://localhost:8080/read?address=0x30&count=4

### Local WRITE ??
GET http://localhost:8080/write?address=0x27&data=ff

### PI READ FAIL
GET http://192.168.178.69:8080/read?address=0&count=4

### PI READ OK
GET http://192.168.178.69:8080/read?address=0x30&count=4

### PI WRITE TO PCF8574
GET http://192.168.178.69:8080/write?address=0x27&data=ff
